### ISSUE TITLE
Nested List Items

### ISSUE THREAD

**Issue by nosbig** [tylerjlawson/simple-resume#1]
While trying to replicate my resume into this simple format, one of my items of experience consists of listing the sections of my responsibility.  For example,

* Responsible for managing the below items:
  * Item 1
  * Item 2
  * Item 3

I would love to have one level of nested bullets in the template in the 'points' template style.  At this time, no combination of bullet styles is available more than a single level of depth.  I've tried using '+', indenting the YAML clauses to another level lower, adding a subordinate 'points' container, using '*', and more.  Each attempt causes Hugo's development server to refuse to process due to a YAML parsing error, requiring me to restart the Hugo development server prior to continuing development.

**Comment by tylersayshi** [comment]
Hi, I found [this SO thread](https://stackoverflow.com/questions/16333975/nested-lists-in-yaml) for how to write YAML with nested lists.

This will stop Hugo's server from crashing, but the template will not render the way you'd want it to. [This is the line where the points are read into the theme](https://github.com/tylerjlawson/simple-resume/blob/master/layouts/partials/section.html#L27), so additional logic would need to be added to support lists with sublists. There may need to be additional styling added [here](https://github.com/tylerjlawson/simple-resume/blob/master/assets/main.scss#L47) depending on how the sublist looks once it is supported.
If you want to try making a Pull Request with updates to support sublists, that would be awesome and I'd be happy to help where needed. Otherwise, I can try to add the functionality for this sometime soon.

**Comment by tylersayshi** [comment]
I went and added support for one level of sublists. I tried doing more levels, but it got increasingly complex, so only one sublevel is supported now.
 [See this commit for the changes and example for how to make a sublist](https://github.com/tylerjlawson/simple-resume/commit/7fae22267110bde22a8ac2946395b7610c0c7d17)
